//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResHun.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorization
    {
        public Authorization()
        {
            this.Employe = new HashSet<Employe>();
        }
    
        public int ID_Authorization { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<int> ID_User { get; set; }
        public Nullable<int> ID_Role { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Employe> Employe { get; set; }
    }
}
