//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResHun.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dishes
    {
        public int ID_Dishes { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> ID_Employe { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> ID_Meat { get; set; }
    
        public virtual Employe Employe { get; set; }
        public virtual Meat Meat { get; set; }
    }
}
