//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResHun.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        public Employe()
        {
            this.Dishes = new HashSet<Dishes>();
        }
    
        public int ID_Employe { get; set; }
        public string FirstName { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public Nullable<int> ID_Post { get; set; }
        public Nullable<int> ID_Authorization { get; set; }
    
        public virtual Authorization Authorization { get; set; }
        public virtual ICollection<Dishes> Dishes { get; set; }
        public virtual Post Post { get; set; }
    }
}
