//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResHun.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meat
    {
        public Meat()
        {
            this.Dishes = new HashSet<Dishes>();
        }
    
        public int ID_Meat { get; set; }
        public string Name { get; set; }
        public Nullable<int> ID_Supliers { get; set; }
    
        public virtual ICollection<Dishes> Dishes { get; set; }
        public virtual Supliers Supliers { get; set; }
    }
}
