//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResHun.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Employe = new HashSet<Employe>();
        }
    
        public int ID_Post { get; set; }
        public string Name { get; set; }
        public string Salary { get; set; }
    
        public virtual ICollection<Employe> Employe { get; set; }
    }
}
