//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResHun.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ID_Reservation { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<int> NumberOrPersons { get; set; }
        public string Event { get; set; }
        public Nullable<int> ID_User { get; set; }
    
        public virtual User User { get; set; }
    }
}
