//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResHun.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supliers
    {
        public Supliers()
        {
            this.Meat = new HashSet<Meat>();
            this.Products = new HashSet<Products>();
        }
    
        public int ID_Supliers { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<Meat> Meat { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}
